replicaCount: 1

image:
  pactImageRepository: pactfoundation/pact-broker
  pactImageTag: 2.79.0.0
  pullPolicy: IfNotPresent

service:
  name: pact-broker
  type: NodePort
  externalPort: 80
  internalPort: 9292
  annotations: {}
    # fabric8.io/expose: "true"
    # fabric8.io/ingress.annotations: "kubernetes.io/ingress.class: alb"

pact:
  port: 9292    

postgresql:

  ## Use the PostgreSQL chart dependency.
  ## Set to false if bringing your own PostgreSQL.
  ##
  enabled: true
  postgresqlUsername: pactbroker
  postgresqlPassword: pactbroker
  postgresqlDatabase: pactbroker

  persistence:
    ## Enable PostgreSQL persistence using Persistent Volume Claims.
    ##
    enabled: true

persistence:
  enabled: true
  accessModes: ReadWriteOnce
  size: 8Gi


ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: alb
    kubernetes.io/tls-acme: "false"
    alb.ingress.kubernetes.io/actions.ssl-redirect: '{"Type": "redirect", "RedirectConfig": { "Protocol": "HTTPS", "Port": "443", "StatusCode": "HTTP_301"}}'
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS": 443}]'
    alb.ingress.kubernetes.io/load-balancer-attributes: 'idle_timeout.timeout_seconds=3600,routing.http2.enabled=false'
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/security-groups: sg-053ebeb7dcfcab552
    alb.ingress.kubernetes.io/tags: 'Application=Krishna-testing,Owner=turir,HoursToLive=1000'
    alb.ingress.kubernetes.io/target-group-attributes: 'stickiness.enabled=true,stickiness.lb_cookie.duration_seconds=3720'
    alb.ingress.kubernetes.io/target-type: ip
    # kubernetes.io/ingress.class: alb
    # kubernetes.io/tls-acme: "true"
  hostname: web-vutus-pact-broker.automation.pega.io

  tls: []
  #  - secretName: pact-broker-tls
  #    hosts:
  #      - pact-broker.local

resources:
  limits:
    cpu: 400m
    memory: 256Mi
  requests:
    cpu: 200m
    memory: 128Mi

probePath: /
livenessProbe:
  initialDelaySeconds: 60
  periodSeconds: 10
  successThreshold: 1
  timeoutSeconds: 1
readinessProbe:
  periodSeconds: 10
  successThreshold: 1
  timeoutSeconds: 1
terminationGracePeriodSeconds: 10
