replicaCount: 1

image:
  pactImageRepository: pactfoundation/pact-broker
  pactImageTag: 2.79.0.0
  pullPolicy: IfNotPresent

service:
  name: pact-broker
  type: NodePort
  externalPort: 80
  internalPort: 9292
  annotations: {}
    # fabric8.io/expose: "true"
    # fabric8.io/ingress.annotations: "kubernetes.io/ingress.class: alb"

pact:
  port: 9292    

postgresql:

  ## Use the PostgreSQL chart dependency.
  ## Set to false if bringing your own PostgreSQL.
  ##
  enabled: true
  postgresUser: pactbroker
  postgresPassword: pactbroker
  postgresDatabase: pactbroker

  persistence:
    ## Enable PostgreSQL persistence using Persistent Volume Claims.
    ##
    enabled: true

persistence:
  enabled: true
  accessMode: ReadWriteOnce
  size: 8Gi


ingress:
  enabled: false
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: pact-broker.pega.com
      paths: []

  tls: []
  #  - secretName: pact-broker-tls
  #    hosts:
  #      - pact-broker.local

resources:
  limits:
    cpu: 400m
    memory: 256Mi
  requests:
    cpu: 200m
    memory: 128Mi

probePath: /
livenessProbe:
  initialDelaySeconds: 60
  periodSeconds: 10
  successThreshold: 1
  timeoutSeconds: 1
readinessProbe:
  periodSeconds: 10
  successThreshold: 1
  timeoutSeconds: 1
terminationGracePeriodSeconds: 10
